name: deutics_attendance_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:  
  sdk: '>=3.4.1 <4.0.0'

dependencies:  
  flutter:    
    sdk: flutter

dev_dependencies:  
  flutter_test:    
    sdk: flutter  
  flutter_lints: ^3.0.0  
  flutter_screenutil: ^5.9.3  
  provider: ^6.1.2  
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0  
  #firebase_auth: ^5.3.1
  firebase_core: ^3.6.0  
  firebase_storage: ^12.3.3  
  shared_preferences: ^2.3.2  
  internet_connectivity_checker: ^1.0.2  
  another_flushbar: ^1.12.30
  google_fonts: ^6.2.1
  circle_nav_bar: ^2.1.0+1
  badges: ^3.1.2
  flutter_text_box: ^0.0.1
  auto_size_text_field: ^2.2.4

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic